### PR TITLE
Deprecate DFIndexer

### PR DESCRIPTION
**Pull request by cmacdonald**
WIP deprecating DFIndexer:

Problems remaining
 - [x]  update indexing.ipynb
 - [x]  fix text.scorer (may require pt.IterDictIndexer to accept memory as a target)

### CODE REVIEW

**Comment by cmacdonald** [comment]
it shows lots of commits, but its only 7 files changed thus far

**Comment by cmacdonald** [comment]
This deprecated DFIndexer. I'm not sure if needs to be rebased, as it shows all the Java branch changes for some reason.

**Comment by seanmacavaney** [comment]
rebased

**Comment by cmacdonald** [comment]
i want to reexecute the notebook without all the INFO log messages before committing

**Comment by cmacdonald** [comment]
I think this can be merged now

**Review by seanmacavaney — APPROVED** [review]
once we see tests pass

**Pull request merged**
