### PR TITLE
addresses #321 pt.apply.doc_score batching

### PR DESCRIPTION
**Pull request by cmacdonald**

### CODE REVIEW

**Comment by cmacdonald** [comment]
Disadvantage with this version: batches can fall across qids. This means that add_ranks() has to be executed on the entire returned dataframe

**Comment by JohnGiorgi** [comment]
I think a slight disadvantage to this is that the caller might have their own batching strategy. 

For example, say you wanted to use `apply_doc_score` with a [Sentence Transformer](https://www.sbert.net/) model either as a retriever or a re-ranker (which I imagine would be a popular use case). Sentence Transformers has a smart batching strategy that batches text of similar length together, so to gain any benefit from that, you would now need to set two batch sizes, `pyterrier_batch_size` >> `sentence_transformers_batch_size`.

One solution would be to add another argument, `batched` (`False` by default), similar to [HF Datasets](https://huggingface.co/docs/datasets/v2.4.0/en/package_reference/main_classes#datasets.Dataset.map.batched), so that:

- If `batched`, then `batch_size` is considered. Otherwise, this is row-wise.
- If `batched` and `batch_size` is `None`, return the whole dataset and let the caller figure out batching.

This is mainly a nitpick though because the same thing could be achieved by setting `batch_size` to the size of the data frame you are applying the transform to.

**Comment by cmacdonald** [comment]
Hi @JohnGiorgi 

We're a bit confused - if the toolkit being called already has batching support, then why need a version of doc_score that performs batching? pt.apply.generic and by_query apply no batching, and could be used when the underlying library does the batching. E.g.

```python

def _scoring_fn(df):
  df["score"] = transformer_library.score_in_own_batches(df["query"], df["text"])

pipe = bm25 >> pt.apply.generic(_scoring_fn)
#pt.apply.by_query could also be used here rather than pt.apply.generic
```

**Comment by JohnGiorgi** [comment]
Okay I think I understand!

My original motivation was to use a Sentence Transformer model as a re-ranker, so I was looking at `doc_score`. But I see your point about using `generic`. The only thing I would need to do (besides implementing the `fn`), is to call `add_ranks`, then>

**Comment by cmacdonald** [comment]
> The only thing I would need to do (besides implementing the fn), is to call add_ranks, then?

yes. Technically add_ranks() is optional, but advised. Applying a rank cutoff with an outdated rank attribute would of course not work.

**Comment by JohnGiorgi** [comment]
Gotcha, okay happy to go this route then. Thanks for the help!

**Comment by cmacdonald** [comment]
Noted. I think the PR still has value, and we can merge it after review.

I think @JohnGiorgi what would be insightful is knowing if the documentation for pt.apply is missing something?

**Comment by JohnGiorgi** [comment]
I think if `pt.apply` is the main way to use custom neural models for retrieval and (re)ranking, it might be helpful to see an example?

**Comment by cmacdonald** [comment]
I added a documentation example for batched `pt.apply.doc_score()`. I think this resolves the request.

**Pull request merged**
