### PR TITLE
add save_mode='warn' and save_mode='error' to pt.Experiment (warn as default)

### PR DESCRIPTION
**Pull request by cmacdonald**
fixes: #304

### CODE REVIEW

**Comment by cmacdonald** [comment]
An alternative default would be a save_mode='warn' method which behaved identically to the current configuration, but warns instead of giving a ValueError

**Comment by cmacdonald** [comment]
thanks jack, food for thought

**Comment by seanmacavaney** [comment]
```
save_mode : SAVEMODE_TYPE = 'error',
```

but the docstring says:

```
Default is "warn".
```

(as does the name of this PR)

**Comment by cmacdonald** [comment]
Fixed

> ```
> save_mode : SAVEMODE_TYPE = 'error',
> ```
> 
> but the docstring says:
> 
> ```
> Default is "warn".
> ```
> 
> (as does the name of this PR)

Fixed

**Review by seanmacavaney — APPROVED** [review]

**Comment by cmacdonald** [comment]
Thanks @albertoueda  @JackMcKechnie and @seanmacavaney for all the suggestions and comments. This is now merged.

**Pull request merged**
