### PR TITLE
More types

### PR DESCRIPTION
**Pull request by cmacdonald**
This PR exposes more types in the PyTerrier API, and fixes various code that mypy thought might be erroneous.
Anything calling jnius is mis-typed, and hence why pyterrier.java.* and pyterrier.terrier.* is ignored.

### CODE REVIEW

**Comment by cmacdonald** [comment]
pyterrier_flake8_ext detects typing.cast as requiring java (false positive).

**Comment by seanmacavaney** [comment]
sorted with `# noqa: PT100`

**Comment by seanmacavaney** [comment]
I added a mypy github action so that we know what issues are remaining here.

**Comment by seanmacavaney** [comment]
amazing! 🥳

**Pull request merged**
