### PR TITLE
Fix PyJnius imports

### PR DESCRIPTION
**Pull request by heinrichreimer**
In the datasets module `pt.autoclass` is imported which doesn't exist.
Replaced it with the direct import from PyJnius.

### CODE REVIEW

**Comment by cmacdonald** [comment]
Thanks for the PR @heinrichreimer 

Do you have a test case for this? pt.autoclass should exist as long as pt.init() has been called - see https://github.com/terrier-org/pyterrier/blob/master/pyterrier/__init__.py#L148.

This code has a lot of testing in the unit tests, so I'm comfortable it works.

**Comment by heinrichreimer** [comment]
Ah I see, I havent called `init()`, my bad

**Comment by cmacdonald** [comment]
> Ah I see, I havent called `init()`, my bad

Correct. `init()` is necessary to ensure appropriate JVM configuration. All we can do is put more checks that things aren't called before init().

**Comment by heinrichreimer** [comment]
Or can we just integrate
```python
if not started():
    init()
```
into the methods that need the JVM to be initialized?

**Comment by heinrichreimer** [comment]
Still I'm a little bit confused as `autoclass` seems to be imported directly from `jnius` [in some places](https://github.com/terrier-org/pyterrier/search?q=jnius+autoclass) and from `pyterrier` [in some other places](https://github.com/terrier-org/pyterrier/search?q=pt+autoclass).

**Comment by cmacdonald** [comment]
> Or can we just integrate
> ```python
> if not started():
>     init()
> ```
> into the methods that need the JVM to be initialized?

We've discussed automatic init internally at length. Auto initiation has some dangerous unintended side-effects - for instance, if multiple libraries use Jnius.

I'm not saying this is a hill I'm willing to die on. But its fairly easy to get used to start with pt.init().

> Still I'm a little bit confused as `autoclass` seems to be imported directly from `jnius` [in some places](https://github.com/terrier-org/pyterrier/search?q=jnius+autoclass) and from `pyterrier` [in some other places](https://github.com/terrier-org/pyterrier/search?q=pt+autoclass).

There is/was some intention to replace jnius with jpype at some point, hence the aliasing. However, there is no marked efficiency benefit, so we backburnered that effort.

**Comment by cmacdonald** [comment]
In your code, you could `assert pt.started()` at the top of the relevant file, e.g. https://github.com/heinrichreimer/chatnoir-pyterrier/blob/main/chatnoir_pyterrier/retrieve.py

**Comment by heinrichreimer** [comment]
> In your code, you could `assert pt.started()` at the top of the relevant file, e.g. https://github.com/heinrichreimer/chatnoir-pyterrier/blob/main/chatnoir_pyterrier/retrieve.py

Very good idea! I'm closing this PR as it's not really needed aymore.

**Pull request closed without merging**
