### PR TITLE
Update pt.terrier.Retriever __str__ and __repr__

### PR DESCRIPTION
**Pull request by cmacdonald**
{wip}

These will be viewable by all users who dont use `names=[]` in -pt.`Experiment()`

### CODE REVIEW

**Comment by cmacdonald** [comment]
Here is what a new new experiment looks like:
```
>>> pt.Experiment([br, br >> pt.rewrite.Bo1QueryExpansion(br.indexref) >> br], dataset.get_topics(), dataset.get_qrels(), ["map"])
                                                name       map
0                                     pt.t.Retr(DPH)  0.283614
1  Compose(Compose(pt.t.Retr(DPH), QueryExpansion...  0.295955
```

**Comment by seanmacavaney** [comment]
Let me think a bit on this...

On the one hand, it's nice to have short, abbreviated names here to be concise.

On the other hand, the current form might look too much like an actual python statement -- and `pt.t.Retr` doesn't exist.

How about `TerrierRetr(DPH)`? Only 2 characters longer.

**Comment by cmacdonald** [comment]
> How about TerrierRetr(DPH)? Only 2 characters longer.

The featured one is much longer of course.

**Comment by seanmacavaney** [comment]
`TerrierFeatRetr`?

**Pull request merged**
